### ISSUE TITLE
Cannot configure programmatically

### ISSUE THREAD

**Issue by gtranchedone** [vapor-community/swiftybeaver-provider#1]
Hi, thanks for the repo. However, this is not really usable as the configuration for the cloud can only be injected using a .json file containing the configuration keys and secrets. Locally it's OK to set up a `Config/secrets/swiftybeaver.json` file, but when deploying that doesn't work if you don't want to store secrets in the project's repo. Could you please add a way to configure the Provider programmatically?

**Comment by gperdomor** [comment]
You can use environment vars in the json, like `server.json` does

```swift
{
    "platform": {
        "appId": "$YOUR_ENV_VAR",
        ...
    }
}
```

**Comment by gtranchedone** [comment]
Oh, I didn't realize that! I'll try.

**Comment by gperdomor** [comment]
Closed... feel free to reopen if necessary
