### ISSUE TITLE
Time format not returning expected result

### ISSUE THREAD

**Issue by NerdsGeeksGurus** [vapor-community/swiftybeaver-provider#10]
The format for the log appears to have something wrong in the way it displays a date/time format.

Under the old vapor/swiftybeaver, I used the following time format:
file.format = "$Dyyyy-MM-dd HH:mm:ss.SSS$d $C$L$c: $M"

to get this:
2017-10-17 17:34:07.879 INFO: GET /
2017-10-17 17:34:07.884 VERBOSE: 0.0.0.0 -- Log test - verbose
2017-10-17 17:34:08.126 INFO: GET /styles/app.css

Under the new (vapor 2 / swiftybeaver-provider), I am set this up using:
"format": "$Dyyyy-MM-dd HH:mm:ss.SSS$d $C$L$c: $M"

The date/time does not display. Instead I get this:
mm:ss.SSS INFO: GET /
mm:ss.SSS VERBOSE: 0.0.0.0 -- Log test - verbose
mm:ss.SSS INFO: GET /styles/app.css

**Comment by gperdomor** [comment]
@NerdsGeeksGurus in your config json, put an space before the dollar sign

```json
[
    {
        "type": "console",
        "format": " $Dyyyy-MM-dd HH:mm:ss.SSS$d $C$L$c: $M"
    }
]
```
 
if you don't put the space, vapor tries to read an environment variable

**Comment by gperdomor** [comment]
Readme was updated to avoid this problem :D...

**Comment by NerdsGeeksGurus** [comment]
It works great. Thanks for all the work you do on this.
